.F
======================================================================
FAIL
 test_fail (test_fail.TestFileFail)
----------------------------------------------------------------------
Traceback (most recent call last)

  File "/Users/yalingliu/Documents/Github/test-repo/test_repo_clone_runner/tests/test_fail.py", line 6, in test_fail
    self.fail("I will fail")
AssertionError
 I will fail

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)